version: '3'
services:
    #########################
    # React Client
    #########################
    client:
        build: ./react-client
        ports:
            - 3001:3000
        volumes:
            - ./react-client/src:/srv/app/react-client/src
            - ./react-client/public:/srv/app/react-client/public
        links:
            - server
        stdin_open: true
        #command: npm start
    #########################
    # Flask Server
    #########################   
    server:
        build: ./flask-server
        ports:
            - 8081:8000
        volumes:
            - ./flask-server:/srv/app/flask-server
        #command: flask run 0.0.0.0:8000